# targets:
#   $default:
#     builders:
#       # Typically the builder key is just the package name, run `pub run build_runner doctor` to check your config.
#       isar_generator:isar_generator:
#         generate_for:
#           # Example glob for only the Dart files under `lib/models`
#           - lib/src/models/*.dart
